#!/bin/sh

if [ ! -d "$GOGS_CUSTOM_CONF_PATH" ]; then
    mkdir -p $GOGS_CUSTOM_CONF_PATH

echo "
[security]
REVERSE_PROXY_AUTHENTICATION_USER = HTTP_X_FORWARDED_USER

[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = true
ENABLE_REVERSE_PROXY_AUTHENTICATION = true
ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true
" >> $GOGS_CUSTOM_CONF
    
fi

exec "$@"
